src/objects/Badge__c.object
<CustomObject>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Candidate_Badge__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Candidate Badges</relationshipLabel>
        <relationshipName>Candidate_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Candidate_Email__c</fullName>
        <label>Candidate Email</label>
        <type>Email</type>
    </fields>
    <label>Candidate Badge</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>User Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Candidate_Restrictions__c.object
<CustomObject>
    <fields>
        <fullName>Domain__c</fullName>
        <description>Email domain - everything after the @ for candidate email addresses.</description>
        <label>Domain</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exclude_Emails__c</fullName>
        <inlineHelpText>If the majority of email addresses in the domain are allowed, list those that are excluded here.</inlineHelpText>
        <label>Exclude Emails</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Include_Emails__c</fullName>
        <inlineHelpText>If only a few email addresses for the domain are allowed, list them here comma seperated.</inlineHelpText>
        <label>Include Emails</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Candidate Restriction</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Candidate Restrictions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Restrictions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Question__c</fullName>
        <label>Training Question</label>
        <referenceTo>Training_Question__c</referenceTo>
        <relationshipLabel>Training Answers</relationshipLabel>
        <relationshipName>Training_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Answer</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Training Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Training Paths</relationshipLabel>
        <relationshipName>Training_Paths</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Training Path</label>
    <nameField>
        <label>Training Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Question__c.object
<CustomObject>
    <fields>
        <fullName>Correct_Answer_Index__c</fullName>
        <label>Correct Answer Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Training_Step__c</fullName>
        <label>Training Step</label>
        <referenceTo>Training_Step__c</referenceTo>
        <relationshipLabel>Training Questions</relationshipLabel>
        <relationshipName>Training_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Question</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Training Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Step__c.object
<CustomObject>
    <fields>
        <fullName>Content_1__c</fullName>
        <label>Content 1</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Content_2__c</fullName>
        <label>Content 2</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Content_3__c</fullName>
        <label>Content 3</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Content_4__c</fullName>
        <label>Content 4</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Content_5__c</fullName>
        <label>Content 5</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Heading_1__c</fullName>
        <label>Heading 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Heading_2__c</fullName>
        <label>Heading 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Heading_3__c</fullName>
        <label>Heading 3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Heading_4__c</fullName>
        <label>Heading 4</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Heading_5__c</fullName>
        <label>Heading 5</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Path__c</fullName>
        <label>Training Path</label>
        <referenceTo>Training_Path__c</referenceTo>
        <relationshipLabel>Training Steps</relationshipLabel>
        <relationshipName>Training_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Step</label>
    <nameField>
        <label>Training Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrainingTestFixtures.cls
@IsTest
public class TrainingTestFixtures 
{
    public static Training_Path__c GetTrainingPath(String name, Id badgeId)
    {
        return GetTrainingPath(name, badgeId, 1);
    }

    public static Training_Path__c GetTrainingPath(String name, Id badgeId, Integer stepCount)
    {
        Training_Path__c path=
            new Training_Path__c(Name=name,
                                 Description__c='Unit Test',
                                 Badge__c=badgeId);
        insert path;

        List<Training_Step__c> steps=new List<Training_Step__c>();
        for (Integer idx=0; idx<stepCount; idx++) {
            Training_Step__c step=
                new Training_Step__c(Name='Unit Test',
                                    Training_Path__c=path.id,
                                     Description__c='Unit Test',
                                     Heading_1__c='Heading 1',
                                     Content_1__c='Content 1',
                                     Heading_2__c='Heading 1',
                                     Content_2__c='Content 1',
                                     Heading_3__c='Heading 1',
                                     Content_3__c='Content 1',
                                     Heading_4__c='Heading 1',
                                     Content_4__c='Content 1',
                                     Heading_5__c='Heading 1',
                                     Content_5__c='Content 1');

            steps.add(step);
        }
        insert steps;

        return path;
    }

    public static Training_Question__c GetTrainingQuestionWithAnswers(Id stepId, String questionText, 
                                                                      Integer index, Integer answerCount)
    {
        Training_Question__c question=new Training_Question__c(Training_Step__c=stepId,
                                                               Question__c=questionText,
                                                               Index__c=index,
                                                               Correct_Answer_Index__c=1);

        insert question;

        List<Training_Answer__c> answers=new List<Training_Answer__c>();
        for (Integer idx=1; idx<=answerCount; idx++) 
        {
            Training_Answer__c answer=new Training_Answer__c(Training_Question__c=question.id,
                                                             Index__c=idx,
                                                             Answer__c='Answer ' + idx);
            answers.add(answer);
        }

        insert answers;

        return question;
    }

    public static Badge__c GetBadge(String name) 
    {
        Badge__c badge=new Badge__c(Name=name);

        insert badge;

        return badge;
    }

    public static Candidate_Restrictions__c GetCandidateRestrictions(String domain,
                                                                     String includeEmails, String excludeEmails)
    {
        Candidate_Restrictions__c cr=new Candidate_Restrictions__c(Domain__c=domain,
                                                                   Include_Emails__c=includeEmails,
                                                                   Exclude_Emails__c=excludeEmails);
        insert cr;

        return cr;
    }

    public static Candidate_Badge__c GetCandidateBadge(Id badgeId, String email)
    {
        Candidate_Badge__c cb=new Candidate_Badge__c(Badge__c=badgeId, Candidate_Email__c=email);
        insert cb;

        return cb;
    }
}