src/objects/Badge__c.object
<CustomObject>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Candidate_Badge__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Candidate Badges</relationshipLabel>
        <relationshipName>Candidate_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Candidate_Email__c</fullName>
        <label>Candidate Email</label>
        <type>Email</type>
    </fields>
    <label>Candidate Badge</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>User Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Candidate_Path__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Email__c</fullName>
        <label>Candidate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <formula>Step_Count__c =  Steps_Completed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_Path__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Training Path</label>
        <referenceTo>Training_Path__c</referenceTo>
        <relationshipLabel>Candidate Paths</relationshipLabel>
        <relationshipName>Candidate_Paths</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Candidate Path</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Candidate Path Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Training Paths</relationshipLabel>
        <relationshipName>Training_Paths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Path</label>
    <nameField>
        <label>Training Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BadgeUtils.cls
public with sharing class BadgeUtils {
    public static void AssignBadgeIfPathComplete(List<Candidate_Path__c> cPaths) 
    {
        Map<Id, List<Candidate_Path__c>> completedByTrainingPathId=new Map<Id, List<Candidate_Path__c>>();
        for (Candidate_Path__c cPath : cPaths)
        {
            if (cPath.Complete__c) 
            {
                List<Candidate_Path__c> cPathsForTr=completedByTrainingPathId.get(cPath.Training_Path__c);
                if (null==cPathsForTr)
                {
                    cPathsForTr=new List<Candidate_Path__c>();
                    completedByTrainingPathId.put(cPath.Training_Path__c, cPathsForTr);
                }
                cPathsForTr.add(cPath);
            }
        }

        List<Id> trPathIds=new List<Id>();
        trPathIds.addAll(completedByTrainingPathId.keySet());
        List<Training_Path__c> trPaths=DataAccessor.GetTrainingPaths(trPathIds);

        Set<Id> badgeIds=new Set<Id>();
        for (Training_Path__c trPath : trPaths)
        {
            badgeIds.add(trPath.Badge__c);
        }

        Map<String, Candidate_Badge__c> candidateBadgesByIdAndEmail=new Map<String, Candidate_Badge__c>();
        for (Candidate_Badge__c cb : DataAccessor.GetCandidateBadges(badgeIds))
        {
            candidateBadgesByIdAndEmail.put(cb.Badge__c + ':' + cb.Candidate_Email__c, cb);
        }

        List<Candidate_Badge__c> cBadges=new List<Candidate_Badge__c>();
        for (Training_Path__c trPath : trPaths) 
        {
            if (null!=trPath.Badge__c)
            {
                List<Candidate_Path__c> cPathsForTr=completedByTrainingPathId.get(trPath.id);
                for (Candidate_Path__c cPath : cPathsForTr)
                {
                    Candidate_Badge__c cBadge = candidateBadgesByIdAndEmail.get(trPath.Badge__c + ':' + cPath.Candidate_Email__c);
                    
                    if (null==cBadge)
                    {
                        cBadge=new Candidate_Badge__c(Candidate_Email__c=cPath.Candidate_Email__c,
                                                                         Badge__c=trPath.Badge__c,
                                                                         Earned_Count__c=1);
                    }
                    else 
                    {
                        if (null==cBadge.Earned_Count__c)
                        {
                            cBadge.Earned_Count__c=1;
                        }
                        cBadge.Earned_Count__c++;
                    }
                    cBadges.add(cBadge);
                }
            }
        }

        upsert cBadges;
    }
}