src/objects/Badge__c.object
<CustomObject>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Training_Question__c</fullName>
        <label>Training Question</label>
        <referenceTo>Training_Question__c</referenceTo>
        <relationshipLabel>Training Answers</relationshipLabel>
        <relationshipName>Training_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Answer</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Training Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Training Paths</relationshipLabel>
        <relationshipName>Training_Paths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Path</label>
    <nameField>
        <label>Training Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Question__c.object
<CustomObject>
    <fields>
        <fullName>Training_Step__c</fullName>
        <label>Training Step</label>
        <referenceTo>Training_Step__c</referenceTo>
        <relationshipLabel>Training Questions</relationshipLabel>
        <relationshipName>Training_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Question</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Training Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Step__c.object
<CustomObject>
    <fields>
        <fullName>Training_Path__c</fullName>
        <label>Training Path</label>
        <referenceTo>Training_Path__c</referenceTo>
        <relationshipLabel>Training Steps</relationshipLabel>
        <relationshipName>Training_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Step</label>
    <nameField>
        <label>Training Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdminTrainingStepController_Test.cls
@isTest
private class AdminTrainingStepController_Test 
{
    @IsTest
    static void CloneStepTest()
    {
        Badge__c badge=TrainingTestFixtures.GetBadge('Test');
        Training_Path__c path=TrainingTestFixtures.GetTrainingPath('Unit Test', badge.id);

        Training_Step__c step=[select id, Training_Path__c from Training_Step__c where Training_Path__c=:path.id];

        Test.startTest();

        Id clonedStepId=AdminTrainingStepController.CloneStep(step.Id);

        Test.stopTest();

        Training_Step__c clonedStep=DataAccessor.GetTrainingStep(clonedStepId);
        System.assertNotEquals(clonedStep.Id, step.Id, 'Id of original and cloned step should be different');
        System.assertEquals(clonedStep.Training_Path__c, step.Training_Path__c, 
                            'Training path for original and cloned step should be identical');

        List<Training_Question__c> questions=DataAccessor.GetTrainingStepQuestions(step.Id);
        List<Training_Question__c> clonedQuestions=DataAccessor.GetTrainingStepQuestions(clonedStepId);

        System.assertEquals(clonedQuestions.size(), questions.size(), 'Should be the same number of questions and cloned questions');

        for (Integer idx=0; idx<questions.size(); idx++)
        {
            Training_Question__c question=questions[idx];
            Training_Question__c clonedQuestion=questions[idx];
            System.assertNotEquals(clonedQuestion.Id, question.Id, 'Question and cloned question ids should be different for index ' + idx);

            System.assertEquals(clonedQuestion.Training_Answers__r.size(), question.Training_Answers__r.size(),
                                'Answers and cloned answers size should be the same for question index ' + idx);

            for (Integer adx=0; adx<question.Training_Answers__r.size(); adx++)
            {
                System.assertNotEquals(clonedQuestion.Training_Answers__r[adx].Id, question.Training_Answers__r[adx].Id, 
                                'Answer and cloned answer ids should be different for index ' + adx);
            }
        }
    }
}