src/objects/Badge__c.object
<CustomObject>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Candidate_Badge__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Candidate Badges</relationshipLabel>
        <relationshipName>Candidate_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Candidate Badge</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>User Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Candidate_Restrictions__c.object
<CustomObject>
    <label>Candidate Restriction</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Candidate Restrictions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Restrictions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Training Paths</relationshipLabel>
        <relationshipName>Training_Paths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Path</label>
    <nameField>
        <label>Training Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Path_Candidate_Restriction__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Restriction__c</fullName>
        <label>Candidate Restriction</label>
        <referenceTo>Candidate_Restrictions__c</referenceTo>
        <relationshipLabel>Training Path Candidate Restrictions</relationshipLabel>
        <relationshipName>Training_Path_Candidate_Restrictions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Training_Path__c</fullName>
        <label>Training Path</label>
        <referenceTo>Training_Path__c</referenceTo>
        <relationshipLabel>Training Path Candidate Restrictions</relationshipLabel>
        <relationshipName>Training_Path_Candidate_Restrictions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Path Candidate Restriction</label>
    <nameField>
        <displayFormat>TPCR-{000000}</displayFormat>
        <label>Training Path Candidate Restriction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Path Candidate Restrictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Step__c.object
<CustomObject>
    <fields>
        <fullName>Training_Path__c</fullName>
        <label>Training Path</label>
        <referenceTo>Training_Path__c</referenceTo>
        <relationshipLabel>Training Steps</relationshipLabel>
        <relationshipName>Training_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Step</label>
    <nameField>
        <label>Training Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrainingServiceImpl_Test.cls
@IsTest
private class TrainingServiceImpl_Test 
{
    @IsTest
    static void GetAllPathsTest()
    {
        Badge__c badge1=TrainingTestFixtures.GetBadge('Test 1');
        Training_Path__c path1=TrainingTestFixtures.GetTrainingPath('Unit Test 1', badge1.id);

        Badge__c badge2=TrainingTestFixtures.GetBadge('Test 2');
        Training_Path__c path2=TrainingTestFixtures.GetTrainingPath('Unit Test 2', badge2.id);

        Candidate_Restrictions__c cr1=TrainingTestFixtures.GetCandidateRestrictions('test.test',
                                                                                   'test@test.test', '');

        Training_Path_Candidate_Restriction__c tpcr1=
                new Training_Path_Candidate_Restriction__c(Training_Path__c=path1.id,
                                                           Candidate_Restriction__c=cr1.id);
        insert tpcr1;

        Candidate_Restrictions__c cr2=TrainingTestFixtures.GetCandidateRestrictions('test.test',
                                                                                   '', 'test@test.test');

        Training_Path_Candidate_Restriction__c tpcr2=
                new Training_Path_Candidate_Restriction__c(Training_Path__c=path2.id,
                                                           Candidate_Restriction__c=cr2.id);
        insert tpcr2;

        TrainingServiceImpl service=new TrainingServiceImpl();

        List<TrainingPath> allPaths=service.GetAllPaths('test@test.test');
        System.assertEquals(1, allPaths.size());
    }

    @IsTest
    static void GetPathTest()
    {
        Badge__c badge1=TrainingTestFixtures.GetBadge('Test 1');
        Training_Path__c tp1=TrainingTestFixtures.GetTrainingPath('Unit Test 1', badge1.id);

        TrainingServiceImpl service=new TrainingServiceImpl();

        TrainingPath path=service.GetPath(tp1.Id, 'test@test.test');
        System.assertNotEquals(null, path);
    }

    @IsTest
    static void GetStepTest()
    {
        Badge__c badge1=TrainingTestFixtures.GetBadge('Test 1');
        Training_Path__c tp1=TrainingTestFixtures.GetTrainingPath('Unit Test 1', badge1.id, 5);
        List<Training_Step__c> steps=[select id from Training_Step__c where Training_Path__c = :tp1.id];
        TrainingTestFixtures.GetTrainingQuestionWithAnswers(steps[2].Id, 'Unit Test', 10, 3);

        TrainingServiceImpl service=new TrainingServiceImpl();

        TrainingPath path=service.GetStep(tp1.Id, steps[2].Id, 'test@test.test');
        System.assertNotEquals(null, path);
        System.assertEquals(5, path.steps.size());
    }

    @IsTest
    static void PassStepTest()
    {
        Badge__c badge1=TrainingTestFixtures.GetBadge('Test 1');
        Training_Path__c tp1=TrainingTestFixtures.GetTrainingPath('Unit Test 1', badge1.id, 1);
        List<Training_Step__c> steps=[select id from Training_Step__c where Training_Path__c = :tp1.id];

        TrainingServiceImpl service=new TrainingServiceImpl();

        Boolean passed=service.PassStep(tp1.Id, steps[0].id, 'test@test.test');
        System.assertEquals(true, passed);
    }

    @IsTest
    static void FailStepAndWaitTest()
    {
        Badge__c badge1=TrainingTestFixtures.GetBadge('Test 1');
        Training_Path__c tp1=TrainingTestFixtures.GetTrainingPath('Unit Test 1', badge1.id, 1);
        tp1.Hours_Between_Attempts__c=2;
        update tp1;

        List<Training_Step__c> steps=[select id from Training_Step__c where Training_Path__c = :tp1.id];

        TrainingServiceImpl service=new TrainingServiceImpl();

        TrainingPath path=service.FailStepAndWait(tp1.Id, steps[0].id, 'test@test.test');

        System.assert(path.lastAttemptTimeMillis<=System.now().getTime());
    }


    @IsTest
    static void GetUserInfoTest()
    {
        Badge__c badge1=TrainingTestFixtures.GetBadge('Test 1');
        Candidate_Badge__c cb=TrainingTestFixtures.GetCandidateBadge(badge1.Id, 'test@test.test');

        TrainingServiceImpl service=new TrainingServiceImpl();

        TrainingUserInfo userInfo=service.GetUserInfo('test@test.test');

        System.assertEquals(userInfo.badgeCount, 1);
    }
}