src/objects/Training_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Question__c</fullName>
        <label>Training Question</label>
        <referenceTo>Training_Question__c</referenceTo>
        <relationshipLabel>Training Answers</relationshipLabel>
        <relationshipName>Training_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Answer</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Training Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Question__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Step__c</fullName>
        <label>Training Step</label>
        <referenceTo>Training_Step__c</referenceTo>
        <relationshipLabel>Training Questions</relationshipLabel>
        <relationshipName>Training_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Question</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Training Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Step__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Step</label>
    <nameField>
        <label>Training Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdminTrainingQuestionController.cls
public with sharing class AdminTrainingQuestionController 
{
    @AuraEnabled 
    public static Id CreateNewQuestionFromStep(String stepIdStr)
    {
        Training_Question__c question=new Training_Question__c(Training_Step__c=stepIdStr);
        insert question;

        return question.Id;
    }

    @AuraEnabled
    public static QuestionAndAnswers GetQuestionAndAnswers(String questionIdStr) 
    {
        Training_Question__c question=DataAccessor.GetQuestion(questionIdStr);
        List<Training_Answer__c> answers=DataAccessor.GetAnswers(question.id);
        System.debug('Answers = ' + answers);
        QuestionAndAnswers result=new QuestionAndAnswers();
        result.question=question;
        result.answers=answers;

        return result;
    }

    @AuraEnabled
    public static QuestionAndAnswers Save(String qandaJSON)
    {
        System.debug('QANDA JSON = ' + qandaJSON);

        QuestionAndAnswers qanda=(QuestionAndAnswers) JSON.deserialize(qandaJSON, QuestionAndAnswers.class);
        System.debug('QANDA = ' + qanda);
        if (null!=qanda.question.Id)
        {
            // figure out if any answers have been deleted

            List<Training_Answer__c> toDelete=new List<Training_Answer__c>();

            // put the new answers with ids into a map
            Map<Id, Training_Answer__c> answersById=new Map<Id, Training_Answer__c>();
            answersById.putAll(qanda.answers);
            System.debug('AnswersById = ' + answersById);

            // get the current answers from the database
            List<Training_Answer__c> answersFromDB=DataAccessor.GetAnswers(qanda.question.Id);
            for (Training_Answer__c answer : answersFromDB)
            {
                System.debug('Looking for answer with id ' + answer.id + ' in map');
                if (null==answersById.get(answer.id))
                {
                    toDelete.add(answer);
                }
            }

            delete toDelete;
        }
        
        // update/insert the question and answers
        upsert qanda.question;

        List<Training_Answer__c> answersToUpsert=new List<Training_Answer__c>();

        for (Training_Answer__c answer : qanda.answers)
        {
            if (null==answer.Id) {
                Training_Answer__c newAnswer=
                            new Training_Answer__c(Answer__c=answer.Answer__c,
                                                   Index__c=answer.Index__c,
                                                   Training_Question__c=qanda.question.id);
                answersToUpsert.add(newAnswer);
            }
            else {
                answersToUpsert.add(answer);
            }
        }

        upsert answersToUpsert;

        return GetQuestionAndAnswers(qanda.question.Id);
    }

    public class QuestionAndAnswers
    {
        @AuraEnabled
        public Training_Question__c question {get; set;}

        @AuraEnabled
        public List<Training_Answer__c> answers {get; set;}

        public QuestionAndAnswers()
        {
            answers=new List<Training_Answer__c>();
        }
    }
}