src/objects/Training_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Training_Question__c</fullName>
        <label>Training Question</label>
        <referenceTo>Training_Question__c</referenceTo>
        <relationshipLabel>Training Answers</relationshipLabel>
        <relationshipName>Training_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Answer</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Training Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Question__c.object
<CustomObject>
    <fields>
        <fullName>Training_Step__c</fullName>
        <label>Training Step</label>
        <referenceTo>Training_Step__c</referenceTo>
        <relationshipLabel>Training Questions</relationshipLabel>
        <relationshipName>Training_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Question</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Training Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Step__c.object
<CustomObject>
    <label>Training Step</label>
    <nameField>
        <label>Training Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdminTrainingStepController.cls
public with sharing class AdminTrainingStepController {
    @AuraEnabled 
    public static Id CloneStep(String stepIdStr)
    {
        Training_Step__c stepToClone=DataAccessor.GetTrainingStep(stepIdStr);
        Map<Id, Training_Question__c> trainingQAndAToCloneById=new Map<Id, Training_Question__c>();
        trainingQAndAToCloneById.putAll(DataAccessor.GetTrainingStepQuestions(stepIdStr));
        
        Training_Step__c step=stepToClone.clone(false, true);
        insert step;

        List<Training_Question__c> questions=new List<Training_Question__c>();

        for (Training_Question__c questionToClone : trainingQAndAToCloneById.values())
        {
            Training_Question__c question=questionToClone.clone(false, true);
            question.Training_Step__c=step.id;
            questions.add(question);
        }

        insert questions;

        Integer idx=0;
        List<Training_Answer__c> answers=new List<Training_Answer__c>();

        for (Training_Question__c questionToClone : trainingQAndAToCloneById.values())
        {
           Training_Question__c question=questions[idx++];
            for (Training_Answer__c answerToClone : questionToClone.Training_Answers__r)
            {
                Training_Answer__c answer=answerToClone.clone(false, true);
                answer.Training_Question__c=question.Id;
                answers.add(answer);
            }
        }

        insert answers;

        return step.Id;
    }
}